# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem,QMenu
from PyQt5.QtCore import Qt
from subclasstablewiget import TableWidget



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 464)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 671, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("button_ig.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 51, 61))
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("dashboard_small.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 32, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        #self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget = TableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 160, 671, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(5)
        # Set the table headers
        self.tableWidget.setHorizontalHeaderLabels(["Status", "NickName", "IP"])
        # Set the table values
        for i in range(5):
            for j in range(3) :
                self.tableWidget.setItem(i, j, QTableWidgetItem("nasir"))
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        #self.tableWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        #self.tableWidget.customContextMenuRequested.connect(self.contextMenuEvent)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    
    #def contextMenuEvent(self, pos):
        #contextMenu = QMenu(self)
        #contextMenu = QMenu()
        #newAct = contextMenu.addAction("New")
        #openAct = contextMenu.addAction("Open")
        #quitAct = contextMenu.addAction("Quit")
       # action = contextMenu.exec_(self.tableWidget.mapToGlobal(pos))
        #contextMenu.popup(self.tableWidget.viewport().mapToGlobal(pos))
       # if action == quitAct:
            #self.close()
            
            
            
            
            
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "SapnilRAT"))

